### ISSUE TITLE
upload is not a function

### ISSUE THREAD

**Issue by Dr-Brains** [orgrimarr/node-wetransfert#1]
When I try to upload a file I get this error:
```
 TypeError: upload is not a function
     at Object.<anonymous> (/Users/DrBrains/Desktop/wetrans.js:2:18)
     at Module._compile (module.js:635:30)
     at Object.Module._extensions..js (module.js:646:10)
     at Module.load (module.js:554:32)
     at tryModuleLoad (module.js:497:12)
     at Function.Module._load (module.js:489:3)
     at Function.Module.runMain (module.js:676:10)
     at startup (bootstrap_node.js:187:16)
     at bootstrap_node.js:608:3
```
I used the example script and edited the file names and email adresses to my own:
```
const { upload, download, getInfo,  isValidWetransfertUrl  } = require('wetransfert');
const myUpload = upload('sender@drbrains.com', ['receiver@drbrains.com'], ['/Users/DrBrains/Desktop/testfile.indd'], 'Uploadscript Test', 'en')
  .on('progress', (progress) => console.log('PROGRESS', progress))
  .on('end', (end) => console.log('END', end))
  .on('error', (error) => console.error('ERROR', error));

  setTimeout(function(){
      myUpload.cancel();
  }, 10000);
```
I just run it with `node wetrans.js`
Pretty new to all this, what am I doing wrong?

**Comment by orgrimarr** [comment]
Sorry, this is a stupid issue, the upload function exist but i didn't export it...
