### ISSUE TITLE
Error : 'not found'

### ISSUE THREAD

**Issue by lyes96** [orgrimarr/node-wetransfert#3]
Hi there, this error is always returned when I run test.js which is located in the wetransfert package. Does it have something to do with the weTransfert module? Can you please help? Thank you :)

ERROR { StatusCodeError: 404 - {"status":"404","error":"Not Found"}
    at new StatusCodeError (C:\Users\lyes.khellaf\Desktop\Delair\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (C:\Users\lyes.khellaf\Desktop\Delair\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\Users\lyes.khellaf\Desktop\Delair\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (C:\Users\lyes.khellaf\Desktop\Delair\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\lyes.khellaf\Desktop\Delair\node_modules\request\request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\lyes.khellaf\Desktop\Delair\node_modules\request\request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - {"status":"404","error":"Not Found"}',
  error: { status: '404', error: 'Not Found' },

**Comment by orgrimarr** [comment]
Hi,

Wetransfer have changed all api paths, this will be patch in the next release

Thanks you for reporting this bug

**Comment by orgrimarr** [comment]
fixed in v2.0.4
