### ISSUE TITLE
Some url not down

### ISSUE THREAD

**Issue by namnh0489** [orgrimarr/node-wetransfert#32]
Hello, 
I was use wetransfert to download file from url. But, there are some urls cant download. Url is public, I can download when access url on browser
url subdomain.wetransfer.com/downloads/...

```
Error: Unhanle url: undefined
    at getInfo (C:\xampp\htdocs\epp-system-node\node_modules\wetransfert\handler\getInfo.js:95:15)
    at C:\xampp\htdocs\epp-system-node\node_modules\wetransfert\handler\download.js:21:45
    at C:\xampp\htdocs\epp-system-node\node_modules\wetransfert\utils\PProgress.js:79:4
    at new Promise (<anonymous>)
    at new PProgress (C:\xampp\htdocs\epp-system-node\node_modules\wetransfert\utils\PProgress.js:78:3)
    at exports.download (C:\xampp\htdocs\epp-system-node\node_modules\wetransfert\handler\download.js:16:12)
    at C:\xampp\htdocs\epp-system-node\schedules\jobNew.js:52:5
    at new Promise (<anonymous>)
    at downloadfile (C:\xampp\htdocs\epp-system-node\schedules\jobNew.js:51:9)
    at handleJob (C:\xampp\htdocs\epp-system-node\schedules\jobNew.js:43:13)
    at async C:\xampp\htdocs\epp-system-node\schedules\jobNew.js:20:9
```
I hope you can fix this problem!

**Comment by orgrimarr** [comment]
Hi,
I wasn't able to fully reproduce your issue, i think i need a payed account in order to have a subdomain.
I just release this version 📦  wetransfert@2.3.7
It allows subdomain url, but i cant can't do end to end tests.

If it still doesn't work for your, can you send me a test download uri that i can use to debug ?

**Comment by namnh0489** [comment]
I upgrade version 2.3.7 but it still error.
```
TypeError: Cannot read property 'uri' of undefined
    at getContentInfos (C:\xampp\htdocs\nodejs\node_modules\wetransfert\handler\getInfo.js:52:46)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getInfo (C:\xampp\htdocs\nodejs\node_modules\wetransfert\handler\getInfo.js:85:27)
    at async exports.downloadPipe (C:\xampp\htdocs\nodejs\node_modules\wetransfert\handler\download.js:77:31)
```
You can  try with this download url:
`https://editproductphoto.wetransfer.com/downloads/0c3e29b2a1a0e5a04de9e2af68a097fb20220413035233/92eb48b2135e77238aa571d3b9cea13020220413035254/3f9a99`
Thank you,

**Comment by orgrimarr** [comment]
Thanks,
I was able to reproduce.
Should work with 📦  wetransfert@2.3.8

**Comment by namnh0489** [comment]
Yes, this issue has been resolved.
Thank for fixed it !
